// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module mac_1_1_s (
        ap_clk,
        ap_rst,
        input_regs_read,
        weight_regs_read,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [15:0] input_regs_read;
input  [15:0] weight_regs_read;
output  [15:0] ap_return;

wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage0;
wire   [15:0] grp_fu_18_p2;
reg   [15:0] input_regs_read_int_reg;
reg   [15:0] weight_regs_read_int_reg;

moblie_net_hmul_1cud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
moblie_net_hmul_1cud_U725(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(input_regs_read_int_reg),
    .din1(weight_regs_read_int_reg),
    .ce(1'b1),
    .dout(grp_fu_18_p2)
);

always @ (posedge ap_clk) begin
    input_regs_read_int_reg <= input_regs_read;
end

always @ (posedge ap_clk) begin
    weight_regs_read_int_reg <= weight_regs_read;
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_return = grp_fu_18_p2;

endmodule //mac_1_1_s
