-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity copy_beta_fmem2buffe is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_betas_AWVALID : OUT STD_LOGIC;
    m_axi_betas_AWREADY : IN STD_LOGIC;
    m_axi_betas_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_betas_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_betas_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_betas_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_betas_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_betas_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_betas_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_betas_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_betas_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_betas_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_betas_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_betas_WVALID : OUT STD_LOGIC;
    m_axi_betas_WREADY : IN STD_LOGIC;
    m_axi_betas_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_betas_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_betas_WLAST : OUT STD_LOGIC;
    m_axi_betas_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_betas_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_betas_ARVALID : OUT STD_LOGIC;
    m_axi_betas_ARREADY : IN STD_LOGIC;
    m_axi_betas_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_betas_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_betas_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_betas_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_betas_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_betas_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_betas_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_betas_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_betas_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_betas_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_betas_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_betas_RVALID : IN STD_LOGIC;
    m_axi_betas_RREADY : OUT STD_LOGIC;
    m_axi_betas_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    m_axi_betas_RLAST : IN STD_LOGIC;
    m_axi_betas_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_betas_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_betas_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_betas_BVALID : IN STD_LOGIC;
    m_axi_betas_BREADY : OUT STD_LOGIC;
    m_axi_betas_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_betas_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_betas_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    betas_offset : IN STD_LOGIC_VECTOR (30 downto 0);
    beta_buffer_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    beta_buffer_V_full_n : IN STD_LOGIC;
    beta_buffer_V_write : OUT STD_LOGIC;
    n : IN STD_LOGIC_VECTOR (9 downto 0);
    beta_cntl_V_din : OUT STD_LOGIC;
    beta_cntl_V_full_n : IN STD_LOGIC;
    beta_cntl_V_write : OUT STD_LOGIC );
end;


architecture behav of copy_beta_fmem2buffe is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal betas_blk_n_AR : STD_LOGIC;
    signal tmp_fu_133_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal betas_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal exitcond_reg_161 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_reg_111 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_ioackin_m_axi_betas_ARREADY : STD_LOGIC;
    signal ap_block_state1_io : BOOLEAN;
    signal exitcond_fu_139_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state8_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal exitcond_reg_161_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal i_3_fu_145_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal tmp_639_reg_170 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state8 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal tmp_178_fu_122_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_reg_ioackin_m_axi_betas_ARREADY : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state8) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state8)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state8);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ioackin_m_axi_betas_ARREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ioackin_m_axi_betas_ARREADY <= ap_const_logic_0;
            else
                if (((tmp_fu_133_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    if (not(((ap_start = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state1_io)))) then 
                        ap_reg_ioackin_m_axi_betas_ARREADY <= ap_const_logic_0;
                    elsif (((m_axi_betas_ARREADY = ap_const_logic_1) and (ap_start = ap_const_logic_1))) then 
                        ap_reg_ioackin_m_axi_betas_ARREADY <= ap_const_logic_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    i_reg_111_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                i_reg_111 <= ap_const_lv3_0;
            elsif (((exitcond_fu_139_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                i_reg_111 <= i_3_fu_145_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                exitcond_reg_161 <= exitcond_fu_139_p2;
                exitcond_reg_161_pp0_iter1_reg <= exitcond_reg_161;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_reg_161 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_639_reg_170 <= m_axi_betas_RDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, tmp_fu_133_p2, ap_enable_reg_pp0_iter1, ap_block_state1_io, exitcond_fu_139_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state1_io))) and (tmp_fu_133_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                elsif ((not(((ap_start = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state1_io))) and (tmp_fu_133_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((exitcond_fu_139_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) and not(((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)) or ((exitcond_fu_139_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(7);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state11 <= ap_CS_fsm(8);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(m_axi_betas_RVALID, ap_enable_reg_pp0_iter1, exitcond_reg_161)
    begin
                ap_block_pp0_stage0_01001 <= ((exitcond_reg_161 = ap_const_lv1_0) and (m_axi_betas_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(m_axi_betas_RVALID, ap_enable_reg_pp0_iter1, exitcond_reg_161)
    begin
                ap_block_pp0_stage0_11001 <= ((exitcond_reg_161 = ap_const_lv1_0) and (m_axi_betas_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(m_axi_betas_RVALID, ap_enable_reg_pp0_iter1, exitcond_reg_161)
    begin
                ap_block_pp0_stage0_subdone <= ((exitcond_reg_161 = ap_const_lv1_0) and (m_axi_betas_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_state10_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state1_io_assign_proc : process(tmp_fu_133_p2, ap_sig_ioackin_m_axi_betas_ARREADY)
    begin
                ap_block_state1_io <= ((tmp_fu_133_p2 = ap_const_lv1_1) and (ap_sig_ioackin_m_axi_betas_ARREADY = ap_const_logic_0));
    end process;

        ap_block_state8_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state9_pp0_stage0_iter1_assign_proc : process(m_axi_betas_RVALID, exitcond_reg_161)
    begin
                ap_block_state9_pp0_stage0_iter1 <= ((exitcond_reg_161 = ap_const_lv1_0) and (m_axi_betas_RVALID = ap_const_logic_0));
    end process;


    ap_condition_pp0_exit_iter0_state8_assign_proc : process(exitcond_fu_139_p2)
    begin
        if ((exitcond_fu_139_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state8 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state8 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_ioackin_m_axi_betas_ARREADY_assign_proc : process(m_axi_betas_ARREADY, ap_reg_ioackin_m_axi_betas_ARREADY)
    begin
        if ((ap_reg_ioackin_m_axi_betas_ARREADY = ap_const_logic_0)) then 
            ap_sig_ioackin_m_axi_betas_ARREADY <= m_axi_betas_ARREADY;
        else 
            ap_sig_ioackin_m_axi_betas_ARREADY <= ap_const_logic_1;
        end if; 
    end process;

    beta_buffer_V_din <= tmp_639_reg_170;

    beta_buffer_V_write_assign_proc : process(beta_buffer_V_full_n, ap_block_pp0_stage0_11001, exitcond_reg_161_pp0_iter1_reg, ap_enable_reg_pp0_iter2)
    begin
        if (((exitcond_reg_161_pp0_iter1_reg = ap_const_lv1_0) and (beta_buffer_V_full_n = ap_const_logic_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            beta_buffer_V_write <= ap_const_logic_1;
        else 
            beta_buffer_V_write <= ap_const_logic_0;
        end if; 
    end process;

    beta_cntl_V_din <= ap_const_logic_0;

    beta_cntl_V_write_assign_proc : process(beta_cntl_V_full_n, ap_CS_fsm_state11)
    begin
        if (((beta_cntl_V_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            beta_cntl_V_write <= ap_const_logic_1;
        else 
            beta_cntl_V_write <= ap_const_logic_0;
        end if; 
    end process;


    betas_blk_n_AR_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_betas_ARREADY, tmp_fu_133_p2)
    begin
        if (((tmp_fu_133_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            betas_blk_n_AR <= m_axi_betas_ARREADY;
        else 
            betas_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    betas_blk_n_R_assign_proc : process(m_axi_betas_RVALID, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, exitcond_reg_161)
    begin
        if (((exitcond_reg_161 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            betas_blk_n_R <= m_axi_betas_RVALID;
        else 
            betas_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    exitcond_fu_139_p2 <= "1" when (i_reg_111 = ap_const_lv3_4) else "0";
    i_3_fu_145_p2 <= std_logic_vector(unsigned(i_reg_111) + unsigned(ap_const_lv3_1));
    m_axi_betas_ARADDR <= tmp_178_fu_122_p1(32 - 1 downto 0);
    m_axi_betas_ARBURST <= ap_const_lv2_0;
    m_axi_betas_ARCACHE <= ap_const_lv4_0;
    m_axi_betas_ARID <= ap_const_lv1_0;
    m_axi_betas_ARLEN <= ap_const_lv32_4;
    m_axi_betas_ARLOCK <= ap_const_lv2_0;
    m_axi_betas_ARPROT <= ap_const_lv3_0;
    m_axi_betas_ARQOS <= ap_const_lv4_0;
    m_axi_betas_ARREGION <= ap_const_lv4_0;
    m_axi_betas_ARSIZE <= ap_const_lv3_0;
    m_axi_betas_ARUSER <= ap_const_lv1_0;

    m_axi_betas_ARVALID_assign_proc : process(ap_start, ap_CS_fsm_state1, tmp_fu_133_p2, ap_reg_ioackin_m_axi_betas_ARREADY)
    begin
        if (((tmp_fu_133_p2 = ap_const_lv1_1) and (ap_reg_ioackin_m_axi_betas_ARREADY = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            m_axi_betas_ARVALID <= ap_const_logic_1;
        else 
            m_axi_betas_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_betas_AWADDR <= ap_const_lv32_0;
    m_axi_betas_AWBURST <= ap_const_lv2_0;
    m_axi_betas_AWCACHE <= ap_const_lv4_0;
    m_axi_betas_AWID <= ap_const_lv1_0;
    m_axi_betas_AWLEN <= ap_const_lv32_0;
    m_axi_betas_AWLOCK <= ap_const_lv2_0;
    m_axi_betas_AWPROT <= ap_const_lv3_0;
    m_axi_betas_AWQOS <= ap_const_lv4_0;
    m_axi_betas_AWREGION <= ap_const_lv4_0;
    m_axi_betas_AWSIZE <= ap_const_lv3_0;
    m_axi_betas_AWUSER <= ap_const_lv1_0;
    m_axi_betas_AWVALID <= ap_const_logic_0;
    m_axi_betas_BREADY <= ap_const_logic_0;

    m_axi_betas_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_reg_161, ap_block_pp0_stage0_11001)
    begin
        if (((exitcond_reg_161 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_betas_RREADY <= ap_const_logic_1;
        else 
            m_axi_betas_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_betas_WDATA <= ap_const_lv16_0;
    m_axi_betas_WID <= ap_const_lv1_0;
    m_axi_betas_WLAST <= ap_const_logic_0;
    m_axi_betas_WSTRB <= ap_const_lv2_0;
    m_axi_betas_WUSER <= ap_const_lv1_0;
    m_axi_betas_WVALID <= ap_const_logic_0;
    tmp_178_fu_122_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(betas_offset),64));
    tmp_fu_133_p2 <= "1" when (n = ap_const_lv10_0) else "0";
end behav;
